name: 'Python Unit Tests'
description: 'Runs python unit tests for the project'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install dependencies
      shell: bash
      env:
        PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
      run: pip install -e .

    - name: Run unit tests
      shell: bash
      run: python -m unittest discover -s tests -t .