name: RLM Auto Versioning

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run Auto Versioning Action
        uses: ./.github/actions/auto-versioning
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}