name: RLM Auto Versioning

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - 'scripts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Python Unit Tests
        uses: ./.github/actions/unit-tests

      - name: Run Auto Versioning Action
        if: success()
        uses: ./.github/actions/auto-versioning
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}